// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeLZwT0qdRzEXlNtVXrSQ2g7AVRMRCDug',
    appId: '1:471321973932:web:a0e22bf0a49058a25d3b09',
    messagingSenderId: '471321973932',
    projectId: 'gradlynk-8460c',
    authDomain: 'gradlynk-8460c.firebaseapp.com',
    databaseURL: 'https://gradlynk-8460c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gradlynk-8460c.appspot.com',
    measurementId: 'G-DRL60TJR29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj8eDqKS6zhAMEUkRcipcWdy7d-kwMPkU',
    appId: '1:471321973932:android:a35baa23b6e8a3a95d3b09',
    messagingSenderId: '471321973932',
    projectId: 'gradlynk-8460c',
    databaseURL: 'https://gradlynk-8460c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gradlynk-8460c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB21y0p-Jg6ruANhHfrzpxyTrnFpdMqhQ0',
    appId: '1:471321973932:ios:89ffa7d102e9db425d3b09',
    messagingSenderId: '471321973932',
    projectId: 'gradlynk-8460c',
    databaseURL: 'https://gradlynk-8460c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gradlynk-8460c.appspot.com',
    iosBundleId: 'com.downtownengineers.gradlynk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB21y0p-Jg6ruANhHfrzpxyTrnFpdMqhQ0',
    appId: '1:471321973932:ios:e3c7abaaf160c72f5d3b09',
    messagingSenderId: '471321973932',
    projectId: 'gradlynk-8460c',
    databaseURL: 'https://gradlynk-8460c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gradlynk-8460c.appspot.com',
    iosBundleId: 'io.flutter.plugins.firebase.messaging',
  );
}
